// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OutputExporter is an autogenerated mock type for the OutputExporter type
type OutputExporter struct {
	mock.Mock
}

// ExportOutput provides a mock function with given fields: key, value
func (_m *OutputExporter) ExportOutput(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for ExportOutput")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutputExporter creates a new instance of OutputExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutputExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutputExporter {
	mock := &OutputExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
